name: my_portfolio
description: >
  A sleek and modern portfolio website built using Flutter. This website
  showcases my skills, projects, and achievements through an interactive
  and visually engaging design.

publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.6.0
  hooks_riverpod: ^2.6.1
  hugeicons:
    hosted: https://onepub.dev/api/kdpxxpsdav/
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

flutter_gen:
