name: my_portfolio
description: >
  A sleek and modern portfolio website built using Flutter. This website
  showcases my skills, projects, and achievements through an interactive
  and visually engaging design.

publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  # figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  flutter_hooks: ^0.20.5
  go_router: ^14.6.0
  hooks_riverpod: ^2.6.1
  # hugeicons:
  #   hosted: https://onepub.dev/api/kdpxxpsdav/
  responsive_builder: ^0.7.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HelveticaNow
      fonts:
        - asset: assets/fonts/HelveticaNowDisplay-Regular.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNowDisplay-RegIta.ttf
          style: italic
        - asset: assets/fonts/HelveticaNowDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNowDisplay-Thin.ttf
          weight: 100

    - family: PPPlayground
      fonts:
        - asset: assets/fonts/PPPlayground-Medium.otf
          weight: 500

    - family: OTYokai
      fonts:
        - asset: assets/fonts/OTYokai-Regular.otf
    - family: PPPangaia
      fonts:
        - asset: assets/fonts/PPPangaia-Medium.otf

flutter_gen:
